"""initial migration

Revision ID: 4a0854834c26
Revises: 
Create Date: 2025-05-21 16:44:33.435451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0854834c26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_speed_driver', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('prefers_quick', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prefers_quick')
        batch_op.drop_column('vehicle_type')
        batch_op.drop_column('is_speed_driver')

    # ### end Alembic commands ###
